### ISSUE TITLE
Feature Request - option to disable time in logging output

### ISSUE THREAD

**Issue by peterhoeg** [crazy-max/ftpgrab#130]
### Behaviour

When running under systemd and thus logging to the journal, the timestamps are duplicated. Once from the journal and once from ftpgrab.

```
Oct 07 09:30:01 dk-ftp-1 pull-xx[3588583]: Wed, 07 Oct 2020 09:30:01 UTC DBG 1 notifier(s) created
```

Ideally ftpgrab would just log the message and not add meta data such as time.

#### Steps to reproduce this issue

1. run under systemd
2. that's it - there is no step 2

#### Expected behaviour

```
Oct 07 09:30:01 dk-ftp-1 pull-xx[3588583]: DBG 1 notifier(s) created
```

### Configuration

* FTPGrab version: 7.1.0
* Platform: linux
* System info: Linux mildred 5.8.11 #1-NixOS SMP Wed Sep 23 11:00:03 UTC 2020 x86_64 GNU/Linux
* Remote FTP: N/A

### Logs

n/a

**Comment by crazy-max** [comment]
@peterhoeg #148

**Comment by crazy-max** [comment]
@peterhoeg To disable timestamp in logs since FTPGrab 7.2.0, see https://crazymax.dev/ftpgrab/usage/cli/#command-line
