### ISSUE TITLE
Feature Request - Add a optional configuration parameter to run custom script when sync is completed.

### ISSUE THREAD

**Issue by tthordarson** [crazy-max/ftpgrab#142]
It would be nice if I could configure FTPGrab to run custom bash script or command upon sync completion. An example of something I would like to do is unrar a archive file. Just suggesting this as a new feature.

**Comment by smozely** [comment]
Hopefully adding more than a +1 to this ... just details of a use case.

I'm using `rednoah/filebot` the watcher image, which isn't perfect at detecting when files are complete ... it waits for a single file to not have been changed for 5 minutes. But when it runs it looks at all files in a directory ... so thats caught me with it processing files that are still being downloaded by ftpgrab, when I've been downloading a bunch of files at once.

Using a script, I'd download files to a temp folder, and then move them once completed ... this would also potentially close #76 and #57 (the third in their list) as well. 

... This could be solved in other ways. Filebot also supports excluding files, intention being you add a suffix to files while downloading, and then rename them once finished. But I think the ability to run a script would be enough

**Comment by tthordarson** [comment]
Thanks for letting me know about this `rednoah/filebot` image. Definitely a workaround for us but it would still be ideal IMO to have the completed sync handling feature directly in FTPGrab :)

**Comment by smozely** [comment]
Oh, I'm not saying this works 100% for me ... I still need something in FTPGrab to make it robust as well.

**Comment by crazy-max** [comment]
@tthordarson Yes this is possible through a new notification handler I can introduce.

**Comment by crazy-max** [comment]
@tthordarson @smozely #147

**Comment by crazy-max** [comment]
@tthordarson @smozely To use the script notification see https://crazymax.dev/ftpgrab/config/notif/script/
