### ISSUE TITLE
[Doc Page] Page instructions "Linux Service" is wrong.

### ISSUE THREAD

**Issue by luigi8bits** [crazy-max/ftpgrab#146]
### Behaviour

In version 7, the environment variables for service Linux was changed (https://github.com/crazy-max/ftpgrab/pull/90)

But these steps of doc :
[https://crazymax.dev/ftpgrab/install/binary/#2-running-from-terminal](https://crazymax.dev/ftpgrab/install/binary/#2-running-from-terminal)
[https://crazymax.dev/ftpgrab/install/linux-service/#using-systemd](https://crazymax.dev/ftpgrab/install/linux-service/#using-systemd)

**the instructions are was not changed for the new environment variable**

#### Steps to reproduce this issue

1. In file `ftpgrab.servicechange` change env var `FTPGRAB_DB` to `FTPGRAB_DB_PATH`

### Configuration

* FTPGrab version (7.1.1) : 
* Platform (windows/linux/freebsd/macos) : Linux 
### Error log that you will see, in case it doesn't change (v7).

> FTL Cannot load configuration error="Failed to decode configuration from environment variables: Failed to decode configuration from environment variables: db cannot be a standalone element (type *config.Db)"

**Comment by crazy-max** [comment]
@luigi8bits You're right! Thanks for your input!

**Comment by crazy-max** [comment]
@luigi8bits Should be fixed.
