### ISSUE TITLE
Cannot create grabber

### ISSUE THREAD

**Issue by joket1999** [crazy-max/ftpgrab#162]
![image](https://user-images.githubusercontent.com/6611880/108583413-3d7dfe80-7374-11eb-870e-d436db8a000c.png)

![image](https://user-images.githubusercontent.com/6611880/108583382-17585e80-7374-11eb-9583-1578b6d93077.png)

**Comment by crazy-max** [comment]
@joket1999 You FTP server `www.test.com` is offline? > `127.0.0.1:21` > `connection refused`
