### ISSUE TITLE
Error: FTL Cannot start [container] (Docker on Synology)

### ISSUE THREAD

**Issue by Chris122AT** [crazy-max/ftpgrab#172]
Hello,

on a Synology NAS, the ftpgrab container stops after a successful run ("INF finished duration=[x ms]") with the following error:
`FTL Cannot start ftpgrab error="end of range (48) above maximum (23): 48`

I set the ENV SCHEDULE="0 0 0 * *". Therefore I thought the container would start without downloading before 00:00. But the container does its job at startup and exits with the error mentioned above.

Where is the error or does the container have to be configured differently in the sSynology docker?

Thank you!

Chris

**Comment by crazy-max** [comment]
@Chris122AT `0 0 0 * *` Third value is day and `0` is not allowed. See https://pkg.go.dev/github.com/robfig/cron?utm_source=godoc#hdr-CRON_Expression_Format for more info.

**Comment by Chris122AT** [comment]
Damn ... all right and thank you for your quick response!!
