### ISSUE TITLE
can't work on folder with "([." carracter

### ISSUE THREAD

**Issue by crep7424** [crazy-max/ftpgrab#189]
### Behaviour
When ftp server has directory name contains "([.", read directory fail.
it seem that ftpgrab add \\ to the directory path.

for a directory nammed "lol.dir" ftpgrab want to retrive "lol\\.dir"

#### Steps to reproduce this issue

1. create a folder with one of following carracter : .[(
2. put a file in the new folder

#### Expected behaviour

> ftpgrab should download the folder and the file

#### Actual behaviour

> it fail to read the directory

### Configuration

* FTPGrab version (5.0.0) : **7.5.0**
* Platform (windows/linux/freebsd/macos) : **Linux Docker**
* System info (type `uname -a`) : **Linux ks 4.19.0-16-amd64 # 1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux**
* Remote FTP (Pure-FTPd) or SFTP (OpenSSH) server: **proftpd**

### Logs

> FTPGrab logs (set --log-level flag to debug and --log-ftp)
```
{"level":"debug","time":"2021-05-18T19:33:38+02:00","message":"MLSD Download/CrystalDiskInfo8_3_2/CdiResource/gadget"}
{"level":"debug","time":"2021-05-18T19:33:38+02:00","message":"150 Opening ASCII mode data connection for MLSD"}
{"level":"debug","time":"2021-05-18T19:33:39+02:00","message":"226 Transfer complete"}
{"level":"debug","time":"2021-05-18T19:33:39+02:00","message":"EPSV"}
{"level":"debug","time":"2021-05-18T19:33:39+02:00","message":"229 Entering Extended Passive Mode (|||55536|)"}
{"level":"debug","time":"2021-05-18T19:33:39+02:00","message":"MLSD Download/lol\\.dir"}
{"level":"debug","time":"2021-05-18T19:33:39+02:00","message":"550 Download/lol\\.dir: No such file or directory"}
{"level":"error","error":"550 Download/lol\\.dir: No such file or directory","source":"Download","time":"2021-05-18T19:33:39+02:00","message":"Cannot read directory Download/lol.dir"}
{"level":"debug","time":"2021-05-18T19:33:39+02:00","message":"EPSV"}
{"level":"debug","time":"2021-05-18T19:33:39+02:00","message":"229 Entering Extended Passive Mode (|||55536|)"}
{"level":"debug","time":"2021-05-18T19:33:39+02:00","message":"MLSD Download/CrystalDiskMark8_0_1"}
{"level":"debug","time":"2021-05-18T19:33:39+02:00","message":"150 Opening ASCII mode data connection for MLSD"}
{"level":"debug","time":"2021-05-18T19:33:39+02:00","message":"226 Transfer complete"}
```

**Comment by crazy-max** [comment]
Same as #201
