### ISSUE TITLE
Docker Container Stops after Finishing

### ISSUE THREAD

**Issue by xLogiiCx** [crazy-max/ftpgrab#192]
Every time the Remote and the local side are finished my docker container stops. 

```
[90mTue, 08 Jun 2021 16:47:32 CEST[0m [32mINF[0m Finished [36mduration=[0m30.33s
[90mTue, 08 Jun 2021 16:47:32 CEST[0m [31mWRN[0m Cannot close server connection [31merror=[0m[31m"read tcp 10.xx.xx.xxx:5xxxx->5.x.x.x:xxxx: use of closed network connection"[0m
```

**Comment by bornryan** [comment]
I concur, we are having the same issue.

**Comment by crazy-max** [comment]
Would need a proper [bug report](https://github.com/crazy-max/ftpgrab/issues/new?assignees=&labels=&template=bug_report.md) to help you out.
