### ISSUE TITLE
Threads & Paralel Mirroing

### ISSUE THREAD

**Issue by delCatta** [crazy-max/ftpgrab#226]
Hi! 
I've a project that is taking around 25 minutes to mirror, which is bottlenecking other services.

I'm running it on a Docker Container. Is there a way to add threads? Or will it be better to make multiple containers to handle different folders?

thanks!

**Comment by crazy-max** [comment]
@delCatta https://github.com/crazy-max/ftpgrab/issues/48#issuecomment-477696847

**Comment by crazy-max** [comment]
> Or will it be better to make multiple containers to handle different folders?

With FTP protocol we would need some kind of shim to handle that.
