### ISSUE TITLE
Temporary folder for downloading files

### ISSUE THREAD

**Issue by Thlb** [crazy-max/ftpgrab#76]
Hi,

Enhancement idea : put currently downloading files/folder in a temporary location, then move it when completed.

Thanks for work 🥇

**Comment by crazy-max** [comment]
Hi @Thlb, LGTM I put this in my backlog.

**Comment by daemqn** [comment]
I "plussoye" this good idea thlb :)

**Comment by crazy-max** [comment]
@Thlb @daemqn #149

**Comment by crazy-max** [comment]
@Thlb @daemqn To first download the files to a temporary location and then move them to the final destination, see https://crazymax.dev/ftpgrab/config/download/#tempfirst
